# Change these first
owner: dreamy-sky-sanctuary # Your GitHub organization or username, where this repository lives
repo: Uptime-DreamySkySanctuary.com # The name of this repository

sites:
  - name: Dreamy Sky Sanctuary Website
    url: https://dreamyskysanctuary.com/
    headers:
      - "Content-Type: application/json"
      - "Origin: Github Uptime"
    icon: https://dreamyskysanctuary.com/public/imgs/icon.webp
    maxResponseTime: 5000 # it will show degraded if it has been more that 50 seconds before it got a response

assignees: # Users to assign downtime issues (optional)
  - Sander1946

status-website:
  cname: status.dreamyskysanctuary.com
  logoUrl: https://dreamyskysanctuary.com/public/imgs/icon.webp
  favicon: https://dreamyskysanctuary.com/public/imgs/icon.webp
  name: Dreamy Sky Sanctuary
  introTitle: "DreamySkySanctuary.com is a self-hosted and maintained web server that is specifically for the discord server"
  introMessage: This page is here to check up on the status of the self-hosted server. The checks are done by GitHub via a template repo called [Upptime](https://github.com/upptime/upptime). There is no server required. [Get your own uptime checker for free!](https://github.com/upptime/upptime)
  navbar:
    - title: Visit The Website
      href: https://dreamyskysanctuary.com/
    - title: Status
      href: https://status.dreamyskysanctuary.com/
    - title: Website Github Repo
      href: https://github.com/$OWNER/DreamySkySanctuary.com
    - title: Uptime Github Repo
      href: https://github.com/$OWNER/$REPO
